definitions:
  hello.Request:
    properties:
      name:
        type: string
    type: object
  hello.Response:
    properties:
      greeting:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: navono007@gmail.com
    name: Xing
  description: go-app API doc
  license: {}
  title: go-app API
  version: "0.1"
paths:
  /hello:
    get:
      consumes:
      - application/octet-stream
      description: this is description
      parameters:
      - description: Request
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/hello.Request'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/hello.Response'
      summary: Say Hello
      tags:
      - hello
swagger: "2.0"
